-- Update Interdiscount product URLs
DO $do$
DECLARE
  sid UUID;
BEGIN
  SELECT id INTO sid FROM shops WHERE slug = 'interdiscount';
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/samsung-galaxy-s26-ultra-enterprise-edition-256-gb-schwarz-6-9-200-mp-5g-0014481886' WHERE product_id = (SELECT id FROM products WHERE slug = 'samsung-galaxy-s26-ultra') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/samsung-galaxy-a56-enterprise-edition-128-gb-awesome-graphite-schwarz-6-7-50-mp-5g-0014286052' WHERE product_id = (SELECT id FROM products WHERE slug = 'samsung-galaxy-a56') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/samsung-galaxy-s25-eu-version-256-gb-navy-blue-6-2-50-mp-5g-0014321829' WHERE product_id = (SELECT id FROM products WHERE slug = 'samsung-galaxy-s25') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/huawei-watch-gt6-pro-46-mm-edelstahl-schwarz-0014351795' WHERE product_id = (SELECT id FROM products WHERE slug = 'huawei-watch-gt-6') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/samsung-galaxy-watch8-classic-bt-eu-version-46-mm-edelstahl-silber-0014364531' WHERE product_id = (SELECT id FROM products WHERE slug = 'samsung-galaxy-watch-8') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/fujifilm-x100vi-40-2-mp-schwarz-0014104455' WHERE product_id = (SELECT id FROM products WHERE slug = 'fujifilm-x100-vi') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/asus-rog-xbox-ally-x-1000-gb-0014358460' WHERE product_id = (SELECT id FROM products WHERE slug = 'asus-rog-ally-x') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/samsung-galaxy-watch8-classic-bt-46-mm-edelstahl-silber-0014327202' WHERE product_id = (SELECT id FROM products WHERE slug = 'samsung-galaxy-watch-8-classic') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/delonghi-magnifica-start-ecam220-31-sb-silber-schwarz-1-8-l-kaffeevollautomat-0011410263' WHERE product_id = (SELECT id FROM products WHERE slug = 'de-longhi-magnifica-s') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/asus-zenbook-s16-um5606ga-sr250w-copilot-pc-16-amd-ryzen-ai-9-32-gb-ram-2000-gb-ssd-grau-0014409894' WHERE product_id = (SELECT id FROM products WHERE slug = 'asus-zenbook-s-16') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/bose-quietcomfort-ultra-2nd-gen-anc-schwarz-0014379209' WHERE product_id = (SELECT id FROM products WHERE slug = 'bose-quietcomfort-ultra') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/insta360-x4-air-starter-bundle-8k-0014378317' WHERE product_id = (SELECT id FROM products WHERE slug = 'insta360-x4') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/canon-eos-r100-rf-s-18-45mm-is-stm-rf-s-55-210mm-is-stm-kit-24-1-mp-aps-c-schwarz-0013899637' WHERE product_id = (SELECT id FROM products WHERE slug = 'canon-eos-r100') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/marshall-stanmore-iii-bluetooth-schwarz-0009778449' WHERE product_id = (SELECT id FROM products WHERE slug = 'marshall-stanmore-iii') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/asus-rog-zephyrus-g16-16-intel-core-ultra-9-32-gb-ram-1000-gb-ssd-weiss-0014215507' WHERE product_id = (SELECT id FROM products WHERE slug = 'asus-rog-zephyrus-g16') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/dyson-multistyler-airwrap-i-d-haarstyler-und-trockner-straight-wavy-0014213655' WHERE product_id = (SELECT id FROM products WHERE slug = 'dyson-airwrap-multi-styler') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/marshall-monitor-iii-anc-creme-0014444939' WHERE product_id = (SELECT id FROM products WHERE slug = 'marshall-monitor-iii') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/dyson-supersonic-nural-1600-w-violett-0014492321' WHERE product_id = (SELECT id FROM products WHERE slug = 'dyson-supersonic-nural') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/sonos-arc-ultra-weiss-9-1-4-kanal-0014230618' WHERE product_id = (SELECT id FROM products WHERE slug = 'sonos-arc-ultra') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/beats-beats-studio-pro-anc-espresso-0013923979' WHERE product_id = (SELECT id FROM products WHERE slug = 'beats-studio-pro') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/canon-eos-r6-mark-iii-rf-24-105-4l-is-usm-kit-32-5-mp-vollformat-schwarz-0014384677' WHERE product_id = (SELECT id FROM products WHERE slug = 'canon-eos-r6-mark-iii') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/marshall-woburn-iii-bluetooth-schwarz-0009765886' WHERE product_id = (SELECT id FROM products WHERE slug = 'marshall-woburn-iii') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/withings-scanwatch-nova-0014092922' WHERE product_id = (SELECT id FROM products WHERE slug = 'withings-scanwatch-nova') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/sony-zv-e10-ii-body-27-mp-aps-c-schwarz-0014171331' WHERE product_id = (SELECT id FROM products WHERE slug = 'sony-zv-e10-ii') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/nikon-z6iii-body-24-5-mp-vollformat-schwarz-0014163907' WHERE product_id = (SELECT id FROM products WHERE slug = 'nikon-z6-iii') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/canon-eos-r5-mark-ii-import-rf-24-105mm-body-45-mp-vollformat-schwarz-0014216964' WHERE product_id = (SELECT id FROM products WHERE slug = 'canon-eos-r5-mark-ii') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/samsung-bespoke-ai-jet-petpro-580-w-0014484167' WHERE product_id = (SELECT id FROM products WHERE slug = 'samsung-bespoke-jet-ai') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/samsung-backcover-galaxy-a36-5g-transparent-0014231869' WHERE product_id = (SELECT id FROM products WHERE slug = 'samsung-galaxy-a36') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/razer-deathadder-v4-pro-niko-edition-maus-kabellos-gaming-mehrfarbig-0014436401' WHERE product_id = (SELECT id FROM products WHERE slug = 'razer-deathadder-v4-pro') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/panasonic-lumix-s5iix-body-24-2-mp-vollformat-schwarz-0013761944' WHERE product_id = (SELECT id FROM products WHERE slug = 'panasonic-lumix-s5-iix') AND shop_id = sid;
  UPDATE product_shops SET product_url = 'https://www.interdiscount.ch/de/product/acer-swift-go-16-ai-oled-sfg16-61-r6ca-16-amd-ryzen-ai-7-32-gb-ram-1000-gb-ssd-grau-0014312363' WHERE product_id = (SELECT id FROM products WHERE slug = 'acer-swift-go-16') AND shop_id = sid;
END $do$;
